// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace controles_de_text
{
	public partial class VoletViewController : NSViewController
	{
		public VoletViewController(IntPtr handle) : base(handle)
		{
		}
	}
}
